### ISSUE TITLE
Elected Contributor Doesn't Have Contract

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1019]
If an Issue is assigned to a person who doesn't have a DEV contract in Self XDSD and **after that** the Issue is added to scope, self-pm will throw an exception:

```java
2021-02-28 10:27:17.694 DEBUG 13407 --- [scheduling-1] c.s.core.managers.StoredProjectManager   : Elected @amihaiemil.
2021-02-28 10:27:17.697 ERROR 13407 --- [scheduling-1] c.selfxdsd.selfpm.ReviewUnassignedTasks  : Problem while reviewing unassigned tasks of Project self-xdsd/self-storage at github

com.selfxdsd.api.exceptions.TasksException$Single$Assign: Task [256] The given contributor doesn't have the needed contract!
	at com.selfxdsd.core.tasks.StoredTask.assign(StoredTask.java:199) ~[self-core-impl-0.0.65.jar!/:na]
	at com.selfxdsd.core.managers.StoredProjectManager.assignTask(StoredProjectManager.java:425) ~[self-core-impl-0.0.65.jar!/:na]
	at com.selfxdsd.core.managers.StoredProjectManager.unassignedTasks(StoredProjectManager.java:387) ~[self-core-impl-0.0.65.jar!/:na]
	at com.selfxdsd.core.projects.StoredProject.resolve(StoredProject.java:188) ~[self-core-impl-0.0.65.jar!/:na]
	at com.selfxdsd.selfpm.ReviewUnassignedTasks.reviewUnassignedTasks(ReviewUnassignedTasks.java:87) ~[classes!/:0.0.5]
	at jdk.internal.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

In this scenario, it should verify that the assignee has the required contract first.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-10T10:35:10.745391``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
