### ISSUE TITLE
PlatformInvoice cannot print RO diacritics

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1089]
Seems like we get the following exception because of the Romanian diacritica:

```java
java.lang.IllegalArgumentException: U+0103 is not available in this font's encoding: MacRomanEncoding with differences
	at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.encode(PDTrueTypeFont.java:393) ~[pdfbox-2.0.22.jar:2.0.22]
	at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:332) ~[pdfbox-2.0.22.jar:2.0.22]
	at org.apache.pdfbox.pdmodel.font.PDFont.getStringWidth(PDFont.java:363) ~[pdfbox-2.0.22.jar:2.0.22]
	at org.apache.pdfbox.pdmodel.interactive.form.PlainText$Paragraph.getLines(PlainText.java:180) ~[pdfbox-2.0.22.jar:2.0.22]
	at org.apache.pdfbox.pdmodel.interactive.form.PlainTextFormatter.format(PlainTextFormatter.java:182) ~[pdfbox-2.0.22.jar:2.0.22]
	at org.apache.pdfbox.pdmodel.interactive.form.AppearanceGeneratorHelper.insertGeneratedAppearance(AppearanceGeneratorHelper.java:534) ~[pdfbox-2.0.22.jar:2.0.22]
	at org.apache.pdfbox.pdmodel.interactive.form.AppearanceGeneratorHelper.setAppearanceContent(AppearanceGeneratorHelper.java:392) ~[pdfbox-2.0.22.jar:2.0.22]
	at org.apache.pdfbox.pdmodel.interactive.form.AppearanceGeneratorHelper.setAppearanceValue(AppearanceGeneratorHelper.java:225) ~[pdfbox-2.0.22.jar:2.0.22]
	at org.apache.pdfbox.pdmodel.interactive.form.PDTextField.constructAppearances(PDTextField.java:264) ~[pdfbox-2.0.22.jar:2.0.22]
	at org.apache.pdfbox.pdmodel.interactive.form.PDTerminalField.applyChange(PDTerminalField.java:228) ~[pdfbox-2.0.22.jar:2.0.22]
	at org.apache.pdfbox.pdmodel.interactive.form.PDTextField.setValue(PDTextField.java:219) ~[pdfbox-2.0.22.jar:2.0.22]
	at com.selfxdsd.core.StoredPlatformInvoice.toPdf(StoredPlatformInvoice.java:221) ~[self-core-impl-0.0.72.jar:na]
```

Let's fix it.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-24T17:12:58.797157``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
