### ISSUE TITLE
Gitlab.follow() throws Json Exception

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1119]
Seems like Gitlab.follow(...) throws an exception:

```java
2021-04-28 16:15:06.511 DEBUG 8831 --- [scheduling-1] com.selfxdsd.core.FollowProjectOwner     : Following PO...
2021-04-28 16:15:07.352 ERROR 8831 --- [scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

javax.json.stream.JsonParsingException: JsonParser#getObject() or JsonParser#getObjectStream() is valid only for START_OBJECT parser state. But current parser state is START_ARRAY
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:114) ~[javax.json-1.1.4.jar!/:1.1.4]
	at com.selfxdsd.core.JsonResources$JsonResponse.asJsonObject(JsonResources.java:351) ~[self-core-impl-0.0.77.jar!/:na]
	at com.selfxdsd.core.Gitlab.findUserId(Gitlab.java:186) ~[self-core-impl-0.0.77.jar!/:na]
	at com.selfxdsd.core.Gitlab.follow(Gitlab.java:149) ~[self-core-impl-0.0.77.jar!/:na]
	at com.selfxdsd.core.FollowProjectOwner.accept(FollowProjectOwner.java:81) ~[self-core-impl-0.0.77.jar!/:na]
	at com.selfxdsd.selfpm.AcceptInvitations.acceptInvitations(AcceptInvitations.java:86) ~[classes!/:0.0.8-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.IllegalStateException: JsonParser#getObject() or JsonParser#getObjectStream() is valid only for START_OBJECT parser state. But current parser state is START_ARRAY
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:171) ~[javax.json-1.1.4.jar!/:1.1.4]
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:112) ~[javax.json-1.1.4.jar!/:1.1.4]
	... 17 common frames omitted
```

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-05-08T13:17:30.586515``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske can you have a look when you have some time pls? :D

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
