### ISSUE TITLE
BindException when making HTTP Calls

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1229]
Sometimes the app fails to make HTTP Requests, due to:

```java
java.net.BindException: Cannot assign requested address
	at java.base/sun.nio.ch.Net.connect0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.connect(Net.java:476) ~[na:na]
	at java.base/sun.nio.ch.Net.connect(Net.java:468) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:692) ~[na:na]
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:165) ~[java.net.http:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:167) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:370) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:127) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:89) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Exchange.java:306) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:438) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:343) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:335) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:347) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:384) ~[java.net.http:na]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2266) ~[na:na]
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:374) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:293) ~[java.net.http:na]
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) ~[na:na]
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:153) ~[java.net.http:na]
	at java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2591) ~[na:na]
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:246) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:632) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:540) ~[java.net.http:na]
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119) ~[java.net.http:na]
	at com.selfxdsd.core.JsonResources$JdkHttp.get(JsonResources.java:271) ~[self-core-impl-0.0.93.jar!/:na]
	at com.selfxdsd.core.ConditionalJsonResources.conditionalGet(ConditionalJsonResources.java:180) ~[self-core-impl-0.0.93.jar!/:na]
```

Most likely, the HTTP client is not closed properly under certain conditions.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-10-09T09:58:32.085474``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
