### ISSUE TITLE
SelfException.toString() throws JsonException

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#634]
Apparently, SelfException.toString() throws an exception:

```java
javax.json.JsonException: A non-empty JSON Pointer must begin with a '/'

	at org.glassfish.json.JsonPointerImpl.<init>(JsonPointerImpl.java:90)
	at org.glassfish.json.JsonProviderImpl.createPointer(JsonProviderImpl.java:218)
	at javax.json.Json.createPointer(Json.java:346)
	at org.glassfish.json.JsonPatchImpl.getPointer(JsonPatchImpl.java:209)
	at org.glassfish.json.JsonPatchImpl.apply(JsonPatchImpl.java:165)
	at org.glassfish.json.JsonPatchImpl.apply(JsonPatchImpl.java:136)
	at com.selfxdsd.api.exceptions.ContractsException$OfContributor.json(ContractsException.java:176)
	at com.selfxdsd.api.exceptions.SelfException.toString(SelfException.java:65)
```

How to reproduce: go to a test which expects a SelfException and comment the "expected": ```@Test //(expected = ...)```.

For example, [this](https://github.com/self-xdsd/self-core/blob/master/self-core-impl/src/test/java/com/selfxdsd/core/contracts/ContributorContractsTestCase.java#L230) test.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.

**Comment by amihaiemil** [comment]
@criske can you have a loot here, when you have some time? :D
