### ISSUE TITLE
Elected Contributor Doesn't Have Contract

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#793]
We have this in the logs:

```java
2020-12-14 11:16:54.034 DEBUG 2224 --- [scheduling-1] c.selfxdsd.selfpm.ReviewUnassignedTasks  : Reviewing unassigned tasks from project Dejeu-Org/Repo1 at github... 
2020-12-14 11:16:54.036 DEBUG 2224 --- [scheduling-1] c.s.core.managers.StoredProjectManager   : Checking the unassigned tasks of project Dejeu-Org/Repo1 at github
2020-12-14 11:16:54.585 DEBUG 2224 --- [scheduling-1] c.s.core.managers.StoredProjectManager   : Elected @MihaiDejeu.
2020-12-14 11:16:54.603 ERROR 2224 --- [scheduling-1] c.selfxdsd.selfpm.ReviewUnassignedTasks  : Problem while reviewing unassigned tasks of Project Dejeu-Org/Repo1 at github

com.selfxdsd.api.exceptions.TasksException$Single$Assign: Task [2] The given contributor doesn't have the needed contract!
	at com.selfxdsd.core.tasks.StoredTask.assign(StoredTask.java:176) ~[self-core-impl-0.0.42.jar!/:na]
	at com.selfxdsd.core.managers.StoredProjectManager.assignTask(StoredProjectManager.java:421) ~[self-core-impl-0.0.42.jar!/:na]
	at com.selfxdsd.core.managers.StoredProjectManager.unassignedTasks(StoredProjectManager.java:383) ~[self-core-impl-0.0.42.jar!/:na]
	at com.selfxdsd.core.projects.StoredProject.resolve(StoredProject.java:185) ~[self-core-impl-0.0.42.jar!/:na]
	at com.selfxdsd.selfpm.ReviewUnassignedTasks.reviewUnassignedTasks(ReviewUnassignedTasks.java:87) ~[classes!/:0.0.4-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

It's a bug, this should never happen. Let's fix it.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T11:19:06.062765``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
